version: '3.1'
services:
    mongodb:
        container_name: mongodb
        image: mongo
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        ports:
          - 27017:27017
    api:
        build: .
        container_name: api
        restart: unless-stopped
        ports:
          - 3000:80
